### ISSUE TITLE
Address reports dependabot alerts

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/output-explorer#606]
From Iain:
I glanced at opensafely-core/reports during George's seminar this morning and noticed that there are 15 open dependabot alerts and seven open PRs that failed CI. I feel we should address the dependabot alerts, even if the future of reports is uncertain.

I see that dependabot alerts no longer feature on the [delivery dashboard][1]. I'm reasonably sure they once did, because seeing them here prompted me to address actions-registry dependabot alerts.

[1]: https://dashboards.opensafely.org/d/acb346db-1a11-4aa5-87af-06d38d87661f/delivery-dashboard?orgId=1

**Comment by StevenMaude** [comment]
# Some notes 

## Python dependencies

I'm almost done with this, for my part. There's only the Django PR #611, for which I think I've fixed the tests, but would like to click around the site before it's merged. I'll do that when I'm next around.

## JS dependencies

The only remaining alerts other than that are JS dependencies, presumably the development ones that don't automatically get PRs created. I'm not sure about pressing the button to create the PRs because:

* it's usually @tomodwyer who reviews these normally
* I *think* the Dependabot auto-merge will just merge them if the CI passes; that might be OK, but best to check

## The open requests-cache PR

This PR #551 is not a security update. I can't merge it because it also requires a new release of osgithub with opensafely-core/osgithub#119 merged, which also uses requests-cache as a dependency and needs the same fix.

## Deployment

We should also confirm that there is a deploy with all the security fixes included; deploys don't happen for auto-merged Dependabot PRs [^1].

[^1]: This is another issue to potentially track. I'd estimate — [based on when real people have made commits as opposed to Dependabot](https://github.com/opensafely-core/reports/graphs/contributors?from=2023-01-01&to=2024-02-08&type=c) — that the deploys in this repository have been happening roughly every 3-6 months.

**Comment by tomodwyer** [comment]
JS and Python deps updated, and deployed as part of https://github.com/opensafely-core/reports/commit/5ebfdb97407597cf6acdfae863528fdac85d0dd6
